### ISSUE TITLE
<mat-form-field color="accent">

### ISSUE THREAD

**Issue by LastDragon-ru** [SaturnTeam/saturn-datepicker#108]
### Actual behavior

We have a theme with primary=red and accent=blue, `<mat-form-field color="accent">` gives a mix of colors:

![image](https://user-images.githubusercontent.com/1329824/65662637-cbea3580-e045-11e9-8553-1e1b3cf6a722.png)

### Workaround

```scss
@mixin sat-datepicker-theme($theme) {
    // ....

    .mat-accent {
        $accent: map-get($theme, accent);

        .mat-calendar-body-begin-range:not(.mat-calendar-body-end-range) {
            background-color: mat-color($accent, 100);
        }

        .mat-calendar-body-end-range:not(.mat-calendar-body-begin-range) {
            background-color: mat-color($accent, 100);
        }

        .mat-calendar-cell-semi-selected {
            background-color: mat-color($accent, 100);
        }

        .mat-calendar-cell-over > .mat-calendar-body-cell-content {
            border-color: mat-color($accent);
        }
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/1329824/65662795-356a4400-e046-11e9-9a10-1d1d74fac6d4.png)

But I'm not sure about these styles, I don't know where they are uses (?). Probably it should be fixed too.
https://github.com/SaturnTeam/saturn-datepicker/blob/2092b4ab99d9b6ccc84364f4dc04468400fb143a/saturn-datepicker/src/_theming.scss#L20-L23
